# Technical Parameters
# ----------------------------------------------------------------------------
#
# The number of pixel the mouse has to move before a drag action is initiated.
cell_min_drag_distance = 15

# The amount of time under which two clicks are considered one double click, in seconds.
double_click_time_limit = 0.5

# Color of the cell overlay
cell_overlay_color = "rgba(0, 120, 255, 50)"

# Margin (in pixels) for the grid widget (width of the scroll bar)
grid_horizontal_margin = 20
# Margin (in pixels) between the grid container and the grid (difference between the
# grid container's width and the cells' width * the number of rows)
grid_vertical_margin = 34

# Tag Tree minimum width
tag_tree_min_width = 75

# Database
database_path = "database.sqlite"

# User defined object
object_class_name = "MyObject"
object_package = "my_object"